"""add admin flag to users

Revision ID: 7661aa2cf132
Revises: aa8d5fc9b454
Create Date: 2026-09-09 02:59:05.638439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7661aa2cf132'
down_revision: Union[str, Sequence[str], None] = 'aa8d5fc9b454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'is_admin')
    # ### end Alembic commands ###
